version: "3"
services:
  db:
    image: postgres:latest
    restart: unless-stopped
    ports:
      - "5432:5432"
    environment:
      - POSTGRES_USER=docker
      - POSTGRES_PASSWORD=docker
      - POSTGRES_DB=Blog
    volumes:
      - db:/var/lib/postgresql/data

volumes:
  db: 
    driver: local

